name: Publish Website

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

jobs:
  Build-Artifact-Action:
    name: Build-Artifact-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build blocks
        run: |
          for dir in $(find plugins -type d -name src); do
            if [ -f "$dir/package.json" ]; then
              echo "Building blocks in $dir"
              pushd "$dir" || exit
              mkdir -p ../build
              npm run build -- --output-path ../build
              popd || exit
            fi
          done
          
      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: wpcom
          path: |
            .
            !style.css 
            !node_modules
            !README.md
            !package.json
            !package-lock.json
            !.git
            !.gitignore
            !src
            !tests
            !.github
